#pragma once
#define CONFIG_BT_ENABLED 1
#define CONFIG_CLASSIC_BT_ENABLED 1
#define CONFIG_BT_A2DP_ENABLED 1
#define CONFIG_BT_AVRC_ENABLED 1
#define CONFIG_BT_SSP_ENABLED 1
#define CONFIG_BT_BLE_ENABLED 0
#define CONFIG_BT_BLUEDROID_ENABLED 1
#define CONFIG_BT_STACK_NO_LOG 1
#define IDF_VER "4.3.7"
